version: 2
jobs:
  build:
    working_directory: ~/docker-presto-cluster
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - setup_remote_docker      

      - run:
          name: Install
          command: |
            apt-get update
            apt-get install build-essential docker.io docker-compose -y

      - run:
          name: Compile
          command: make


  deploy:
    working_directory: ~/docker-presto-cluster
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - setup_remote_docker      

      - run:
          name: Install
          command: |
            apt-get update
            apt-get install build-essential docker.io docker-compose -y

      - run:
          name: Compile
          command: make

      - run:
          name: Deploy
          command: make push

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]*/
            branches:
              ignore: /.*/