version: 2
jobs:
  build:
    working_directory: ~/docker-presto-cluster
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker      

      - run:
          name: Compile
          command: make


  deploy:
    working_directory: ~/docker-presto-cluster
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker      

      - run:
          name: Compile
          command: make

      - run:
          name: Login
          command: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

      - run:
          name: Deploy
          command: make push

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]*/
            branches:
              ignore: /.*/